kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/JeetRH/FlaskAPI.git'
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '1843786'
  name: flask-api-git
  uid: 40ed3a84-ec25-4241-93ce-0daa9cd7dbc4
  creationTimestamp: '2022-02-11T01:48:14Z'
  generation: 5
  managedFields:
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2022-02-11T01:48:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:triggers': {}
        'f:status':
          'f:imageChangeTriggers': {}
          'f:lastVersion': {}
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2022-02-11T02:34:10Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:output':
            'f:to':
              .: {}
              'f:kind': {}
              'f:name': {}
          'f:runPolicy': {}
          'f:source':
            'f:contextDir': {}
            'f:git':
              .: {}
              'f:ref': {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:sourceStrategy':
              .: {}
              'f:from':
                .: {}
                'f:kind': {}
                'f:name': {}
                'f:namespace': {}
            'f:type': {}
  namespace: odh-j
  labels:
    app: flask-api-git
    app.kubernetes.io/component: flask-api-git
    app.kubernetes.io/instance: flask-api-git
    app.kubernetes.io/name: flask-api-git
    app.kubernetes.io/part-of: example-python-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi7
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'flask-api-git:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.8-ubi7'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/JeetRH/FlaskAPI.git'
      ref: main
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: flask-api-git-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: flask-api-git-github-webhook-secret
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/python@sha256:7fab39e4a2d880190c8285576314fdb4212feea0d79c269ebaa4dd2d1491c197
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 3
  imageChangeTriggers:
    - lastTriggeredImageID: >-
        image-registry.openshift-image-registry.svc:5000/openshift/python@sha256:7fab39e4a2d880190c8285576314fdb4212feea0d79c269ebaa4dd2d1491c197
      from:
        namespace: openshift
        name: 'python:3.8-ubi7'
      lastTriggerTime: null
